export const LABELS = {
  ALLE_INGREDIENTEN: "Alle ingrediënen",
  BARCODE: "Barcode",
  EMAIL: "E-mail",
  FOUT_MISSENDE_INFO: "Fout of missende informatie",
  GEEN_BARCODE_GEVONDEN: "Geen barcode gevonden",
  GEEN_TOESTEMMING_CAMERA: "Geen toestemming voor camera ontvangen",
  GESCAND_PRODUCT: "Gescand product",
  HALAL: "Halal",
  HARAM_INGREDIENTEN: "Haram ingrediënten",
  HARAM: "Haram",
  SAVE: "Opslaan",
  HANAFI: "Hanafi",
  MALIKI: "Maliki",
  SHAFI: "Shafi",
  HANBALI: "Hanbali",
  NO_SCHOOL_OF_THOUGHT: "Geen wetschool",
  INCORRECT_INGREDIENTEN: "Incorrect ingrediënten",
  INCORRECT_PRODUCT_NAAM: "Incorrect product naam",
  INGREDIENT_ONTBREEKT: "Ingrediënt ontbreekt",
  INGREDIENTEN: "Ingrediënten",
  KIES_REDEN: "Selecteer reden van melden",
  LOG_OUT: "Uitloggen",
  MAAK_FOTO_VAN_INGREDIENTEN: "Maak foto van ingrediënten",
  NEW_PRODUCT_ADDED_SUCCESS: "Nieuw product is toegevoegd. Bedankt!",
  NIET_GEVONDEN: "Niet gevonden",
  NIET_HALAL: "Dit product is niet halal",
  NIET_HARAM: "Dit product is niet haram",
  OPNIEUW_SCANNEN: "Opnieuw scannen",
  PRODUCT_FOUT_MELDEN: "Product fout melden",
  PRODUCT_MET_BARCODE: "Product met barcode",
  PRODUCT_NAAM: "Product naam",
  PRODUCT_REPORT_SENT_DESC: "JazakAllahu khairan. Uw melding wordt spoedig bekeken in sha Allah",
  PRODUCT_REPORT_SENT: "Product melding verstuurd",
  PRODUCT_TOEVOEGEN: "Product toevoegen",
  PRODUCT_TWIJFELACHTIG: "Dit product is twijfelachtig",
  REGISTREREN: "Registreren",
  SCAN_BARCODE: "Scan barcode",
  SCAN_EEN_PRODUCT: "Scan een product",
  SCHOOL_OF_THOUGHT: "Wetschool",
  CHOOSE_SCHOOL_OF_THOUGHT: "Welke wetschool volg je?",
  ARE_YOU_SURE_LOG_OUT: "Weet je zeker dat je wilt uitloggen?",
  AKKOORD: "Akkoord",
  PRODUCT_BESTAAT_AL: "Nieuw product is al toegevoegd met deze barcode",
  SLUITEN: "Sluiten",
  TERUG: "Terug",
  TOELICHTING: "Toelichting",
  TOESTEMMING_CAMERA_AANVRAAG: "Aanvraag voor toestemming gebruik van camera",
  TWIJFELACHTIG: "Twijfelachtig",
  TWIJFELACHTIGE_INGREDIENTEN: "Twijfelachtige ingrediënten",
  USERNAME: "Gebruikersnaam",
  VERZENDEN: "Verzenden",
  VOEG_INGREDIENTEN_TOE: "Voeg ingrediënten toe (1 per regel)",
  VUL_UW_TOELICHTING_TOE: "Vul uw toelichting toe in max 200 tekens",
  PASSWORD: "Wachtwoord",
  LOG_IN: "Inloggen",
  FORGOT_PASSWORD: "Wachtwoord vergeten?",
  VEGAN: "Vegan",
};
