export const LABELS = {
  INGREDIENTEN: "Ingrediënten",
  TOELICHTING: "Toelichting",
  TWIJFELACHTIGE_INGREDIENTEN: "Twijfelachtige ingrediënten",
  SCAN_BARCODE: "Scan barcode",
  GESCAND_PRODUCT: "Gescand product",
  PRODUCT_MET_BARCODE: "Product met barcode",
  NIET_GEVONDEN: "Niet gevonden",
  OPNIEUW_SCANNEN: "Opnieuw scannen",
  PRODUCT_FOUT_MELDEN: "Product fout melden",
  INCORRECT_PRODUCT_NAAM: "Incorrect product naam",
  INCORRECT_INGREDIENTEN: "Incorrect ingrediënten",
  FOUT_MISSENDE_INFO: "Fout of missende informatie",
  NIET_HALAL: "Dit product is niet halal",
  NIET_HARAM: "Dit product is niet haram",
  SLUITEN: "Sluiten",
  PRODUCT_TWIJFELACHTIG: "Product twijfelachtig",
  INGREDIENT_ONTBREEKT: "Ingredient ontbreekt",
  KIES_REDEN: "Selecteer reden van melden",
  VERZENDEN: "Verzenden",
  BARCODE: "Barcode",
  GEEN_TOESTEMMING_CAMERA: "Geen toestemming voor camera ontvangen",
  TOESTEMMING_CAMERA_AANVRAAG: "Aanvraag voor toestemming gebruik van camera",
};
