export const LABELS = {
  EEN_INGREDIENT_PER_REGEL: "Één ingredient per regel",
  CONTACT: {
    WIE_ZIJN_WIJ: {
      TITLE: "Wie zijn wij?",
      DESC: "Deze app is gebouwd door een kleine groep broeders met een frustratie voor het constant moeten lezen en zoeken welke ingredienten er in een product zitten. Vrijwel alle apps op de markt zijn onbetrouwbare of hebben incomplete data en wij besloten dus dit probleem op te lossen.",
    },
    MISSIE_EN_VISIE: {
      TITLE: "Missie en visie",
      DESC: "Onze missie is de moslim gemeenschap te voorzien van een betrouwbare bron van informatie over de halal status van producten op een makkelijke, snelle en toegankelijk manier. \n\nWij zijn voorstanders van transparantie en vrijheid. We willen laten zien hoe we de status van ingredienten bepalen en de gebruiker vrijheid bieden in de mening van de wetschool te volgen die hij of zij wilt.",
    },
    MADHAHIB: {
      DESC: "Wij hebben een halal framework opgesteld die rekening houdt met de verschillende wetscholen. \n\nDit framework is een verzameling van de meest populaire standpunten binnen de wetscholen over specifieke ingredienten. \n\nWe zijn van plan dit framework in de nabije toekomst uit te brengen in het kader van transparantie. We zijn nog in het proces om dit framework door meerdere geleerden te laten verifiëren.",
      TITLE: "Wetscholen en halal framework",
    },
    CONTACT: {
      TITLE: "Contact",
      DESC: "Heb je vragen of feedback? \n\nStuur ons een bericht op X: \n@sheikhhalalnl \n\nOf mail naar: \nsheikhhalalr@gmail.com",
    },
  },
  WIE_ZIJN_WIJ: "Wie zijn wij?",
  ALLERGIEEN: "Allergieën",
  ALLE_INGREDIENTEN: "Alle ingrediënten",
  BARCODE: "Barcode",
  EMAIL: "E-mail",
  FAQ: "FAQ",
  DETECTEER_WOORDEN: "Detecteer woorden",
  VOEG_EEN_WOORD_TOE: "Voeg een woord toe",
  FOUT_MISSENDE_INFO: "Fout of missende informatie",
  GEEN_BARCODE_GEVONDEN: "Geen barcode gevonden",
  GEEN_TOESTEMMING_CAMERA: "Geen toestemming voor camera ontvangen",
  GESCAND_PRODUCT: "Gescand product",
  HALAL: "Halal",
  HARAM_INGREDIENTEN: "Haram ingrediënten",
  HARAM: "Haram",
  SAVE: "Opslaan",
  HANAFI: "Hanafi",
  MALIKI: "Maliki",
  SHAFI: "Shafi",
  HANBALI: "Hanbali",
  NO_SCHOOL_OF_THOUGHT: "Geen wetschool",
  INCORRECT_PRODUCT_NAAM: "Incorrect product naam",
  INGREDIENT_ONTBREEKT: "Ingrediënt ontbreekt",
  INGREDIENTEN: "Ingrediënten",
  KIES_REDEN: "Selecteer reden van melden",
  LOG_OUT: "Uitloggen",
  MAAK_FOTO_VAN_INGREDIENTEN: "Voeg ingredienten toe als foto",
  NEW_PRODUCT_ADDED_SUCCESS: "Nieuw product is toegevoegd. Bedankt!",
  NIET_GEVONDEN: "Niet gevonden",
  NIET_HALAL: "Dit product is niet halal",
  TWIJFELACHTIGE_INGREDIENTEN: "Twijfelachtige ingrediënten",
  NIET_HARAM: "Dit product is niet haram",
  OPNIEUW_SCANNEN: "Opnieuw scannen",
  PRODUCT_FOUT_MELDEN: "Product fout melden",
  PRODUCT_MET_BARCODE: "Product met barcode",
  PRODUCT_NAAM: "Product naam",
  PRODUCT_REPORT_SENT_DESC: "JazakAllahu khairan. Uw melding wordt spoedig bekeken in sha Allah",
  PRODUCT_REPORT_SENT: "Product melding verstuurd",
  PRODUCT_TOEVOEGEN: "Product toevoegen",
  PRODUCT_TWIJFELACHTIG: "Dit product is twijfelachtig",
  REGISTREREN: "Registreren",
  SCAN_BARCODE: "Scan barcode",
  SCAN_EEN_PRODUCT: "Scan een product",
  SCHOOL_OF_THOUGHT: "Wetschool",
  CHOOSE_SCHOOL_OF_THOUGHT: "Welke wetschool volg je?",
  ARE_YOU_SURE_LOG_OUT: "Weet je zeker dat je wilt uitloggen?",
  AKKOORD: "Akkoord",
  PRODUCT_BESTAAT_AL: "Nieuw product is al toegevoegd met deze barcode",
  TERUG: "Terug",
  TOELICHTING: "Toelichting",
  TOESTEMMING_CAMERA_AANVRAAG: "Aanvraag voor toestemming gebruik van camera",
  HARAM_DOOR_ONBEKENDE_OORSPRONG: "Haram door onbekende oorsprong",
  USERNAME: "Gebruikersnaam",
  VERZENDEN: "Verzenden",
  VOEG_INGREDIENTEN_TOE: "Voeg ingrediënten toe",
  VUL_UW_TOELICHTING_TOE: "Vul uw toelichting toe",
  PASSWORD: "Wachtwoord",
  LOG_IN: "Inloggen",
  FORGOT_PASSWORD: "Wachtwoord vergeten?",
  VEGAN: "Vegan",
};
